server:
  port: 8081
  tomcat:
    uri-encoding: utf-8

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  thymeleaf:
    cache: false
  profiles:
    active: dev
mybatis:
  type-aliases-package: com.feidian.xiang.webfinal.dao.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

